vs_cms_images_get_file:
    path: /images/{file}
    controller: Vankosoft\CmsBundle\Controller\GetImageController::getFile
    requirements:
        file: .+

vs_cms_images_filesystem_get_file:
    path: /images-filesystem/{file}
    controller: Vankosoft\CmsBundle\Controller\GetImageController::getFilesystemFile
    requirements:
        file: .+


