vs_cms_document_categories:
    resource: |
        alias: vs_cms.document_categories
        path: /document-categories
        templates: "@VSCms/Pages/Document_Categories"
    type: sylius.resource

vs_cms_document:
    resource: |
        alias: vs_cms.document
        path: /documents
        templates: "@VSCms/Pages/Document"
        form:
            options:
                ckeditor_uiColor: '%vs_cms.form.toc_page.ckeditor_uiColor%'
                ckeditor_toolbar: '%vs_cms.form.toc_page.ckeditor_toolbar%'
                ckeditor_extraPlugins: '%vs_cms.form.toc_page.ckeditor_extraPlugins%'
                ckeditor_removeButtons: '%vs_cms.form.toc_page.ckeditor_removeButtons%'
                ckeditor_allowedContent: '%vs_cms.form.toc_page.ckeditor_allowedContent%'
                ckeditor_extraAllowedContent: '%vs_cms.form.toc_page.ckeditor_extraAllowedContent%'
    type: sylius.resource
    options:
        expose: true

vs_cms_toc_page_index:
    path: /toc-pages/{documentId}/
    methods: [GET]
    defaults:
        _controller: vs_cms.controller.toc_page:indexAction
        _sylius:
            paginate: 30
            sorting:
                score: desc
            filterable: true
            criteria:
                document: $documentId
            template: "@VSCms/Pages/TocPage/index.html.twig"
    options:
        expose: true
        
vs_cms_toc_page:
    resource: |
        alias: vs_cms.toc_page
        path: /toc-pages/{documentId}
        templates: "@VSCms/Pages/TocPage"
        form:
            options:
                ckeditor_uiColor: '%vs_cms.form.toc_page.ckeditor_uiColor%'
                ckeditor_toolbar: '%vs_cms.form.toc_page.ckeditor_toolbar%'
                ckeditor_extraPlugins: '%vs_cms.form.toc_page.ckeditor_extraPlugins%'
                ckeditor_removeButtons: '%vs_cms.form.toc_page.ckeditor_removeButtons%'
                ckeditor_allowedContent: '%vs_cms.form.toc_page.ckeditor_allowedContent%'
                ckeditor_extraAllowedContent: '%vs_cms.form.toc_page.ckeditor_extraAllowedContent%'
    type: sylius.resource
    options:
        expose: true

vs_cms_multipage_toc_page_gtreetable:
    path: /multipage-toc-{documentId}-gtreetable
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::gtreeTableSource

vs_cms_multipage_toc_page_easyui_combotree:
    path: /multipage-toc-{documentId}-easyui-combotree
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::easyuiComboTreeSource
    
vs_cms_multipage_toc_page_sort_action:
    path: /multipage-toc-sort/{id}/{insertAfterId}
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::sortAction
    options:
        expose: true

vs_cms_multipage_toc_page_edit:
    path: /multipage-toc-edit/{documentId}/{tocPageId}/{locale}
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::editTocPage
    defaults: { locale: '%locale%' }
    
vs_cms_multipage_toc_page_delete:
    path: /multipage-toc-delete/{documentId}/{tocPageId}
    controller: Vankosoft\CmsBundle\Controller\MultiPageTocPageController::deleteTocPage


