services:

    # https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/frameworks/symfony.md
    ##################################################################################################
    stof_doctrine_extensions.listener.loggable:
        class: Vankosoft\ApplicationBundle\EventSubscriber\LoggableListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
            - { name: doctrine.event_listener, event: 'postPersist' }
