services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_application.project_issues:
        class: Vankosoft\ApplicationBundle\Component\ProjectIssue\ProjectIssue
        arguments:
            - '@http_client'
            - '@vs_application.doctrine_dbal_cache'
            - {
                host: '%vs_application.vankosoft_api.host%',
                user: '%vs_application.vankosoft_api.user%',
                password: '%vs_application.vankosoft_api.password%',
            }
            - '%vs_application.vankosoft_api.project%'
            - '%vs_application.vankosoft_api.kanbanboard%'
    
    Vankosoft\ApplicationBundle\Controller\VankosoftIssueController:
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_application.project_issues'
    
    Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController:
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_application.project_issues'
    
    Vankosoft\ApplicationBundle\Form\ProjectIssueForm:
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.form.use_ckeditor%'
            - '%vs_cms.form.decription_field.ckeditor5_editor%'
    
    Vankosoft\ApplicationBundle\Form\KanbanboardTaskForm:
        tags:
            - { name: form.type }
