services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Make Themes Repository public to can get it from Container
    vs_app.theme_repository:
        alias: sylius.repository.theme
        public: true
        
    # Since sylius/theme-bundle 2.0: "sylius.theme.context.settable" service is deprecated since Sylius/ThemeBundle 2.0 and will be 
    # removed in 3.0. It is being referenced by the "vs_app.listener.theme_change" service.
    #
    # Since sylius/theme-bundle 2.0: "sylius.repository.theme" service is deprecated since Sylius/ThemeBundle 2.0 and will be 
    # removed in 3.0. It is being referenced by the "vs_app.listener.theme_change" service.
    vs_app.listener.theme_change:
        class: Vankosoft\ApplicationBundle\EventListener\ThemeChangeListener
        arguments:
            - '@sylius.theme.context.settable'
            - '@sylius.repository.theme'
            - '@vs_application.repository.settings'
            - '@vs_application.context.application'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
