services:
    Vankosoft\ApplicationBundle\Twig\ReadableFilesizeExtension:
        tags: ['twig.extension']
        
    Vankosoft\ApplicationBundle\Twig\VsTagsExtension:
        tags: ['twig.extension']
        
    Vankosoft\ApplicationBundle\Twig\FunctionsExtension:
        arguments:
            - '@parameter_bag'
        tags: ['twig.extension']
