services:
    _defaults:
        autowire: true
        autoconfigure: true

    Vankosoft\CmsBundle\Controller\GetImageController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - "@liip_imagine.binary.loader.default"
            - "@liip_imagine.filter.manager"

    Vankosoft\CmsBundle\Controller\PagesCategoryExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@translator'
            - '@vs_cms.repository.page_categories'
    
    Vankosoft\CmsBundle\Controller\PagesExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'
            - '@vs_cms.repository.pages'
            - '@vs_cms.repository.page_categories'
            - '@vs_application.repository.logentry'
            - '@vs_cms.factory.pages'
            - '@vs_application.repository.tags_whitelist_context'
            
    Vankosoft\CmsBundle\Controller\MultiPageTocPageController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.document'
            - '@vs_cms.repository.toc_page'
            - '@vs_cms.factory.toc_page'

    Vankosoft\CmsBundle\Controller\ArtgrisFileManagerController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_cms.file_manager'
    
    Vankosoft\CmsBundle\Controller\VankosoftFileManagerExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.file_manager'
            - '@vs_cms.repository.file_manager_file'
            - '@vs_cms.factory.file_manager_file'
            - '@vs_cms.file_manager'
            
    Vankosoft\CmsBundle\Controller\SliderItemExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.slider'
            - '@vs_cms.repository.slider_item'
            - '@vs_cms.factory.slider_item'
            - '@vs_cms.file_manager'
            - '%vs_application_slider_photo_description%'
    
    Vankosoft\CmsBundle\Controller\BannerExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_cms.repository.banner_place'
            - '@vs_cms.repository.banner'
            - '@vs_cms.factory.banner'
            - '@vs_cms.file_manager'
