parameters:
    # Description Field Form Options
    ##########################################################
    vs_cms.form.decription_field.ckeditor_uiColor: '#ffffff'
    vs_cms.form.decription_field.ckeditor_extraAllowedContent: '*[*]{*}(*)'
    vs_cms.form.decription_field.ckeditor_toolbar: description_toolbar
    vs_cms.form.decription_field.ckeditor_extraPlugins: 'font, justify'
    vs_cms.form.decription_field.ckeditor_removeButtons: ''
    vs_cms.form.decription_field.ckeditor_allowedContent: true
    
    # Pages Form Options
    ##########################################################
    vs_cms.form.pages.ckeditor_uiColor: '#ffffff'
    vs_cms.form.pages.ckeditor_toolbar: devpage_toolbar
    vs_cms.form.pages.ckeditor_extraPlugins: 'font, justify, codesnippet, lightbox'
    vs_cms.form.pages.ckeditor_removeButtons: ''
    vs_cms.form.pages.ckeditor_allowedContent: true # Disable Advanced Content Filter
    vs_cms.form.pages.ckeditor_extraAllowedContent: 'div(*)'
    
    # TocPage Form Options
    ##########################################################
    vs_cms.form.toc_page.ckeditor_uiColor: '#ffffff'
    vs_cms.form.toc_page.ckeditor_toolbar: devpage_toolbar
    vs_cms.form.toc_page.ckeditor_extraPlugins: 'liststyle, font, justify, codesnippet, lightbox, simplebox, simplebox-2, ckeditor_add_class'
    vs_cms.form.toc_page.ckeditor_removeButtons: ''
    vs_cms.form.toc_page.ckeditor_allowedContent: true # Disable Advanced Content Filter
    vs_cms.form.toc_page.ckeditor_extraAllowedContent: '*[*]{*}(*)'
    
services:

    ##########################################################
    # Override Symfony Service '@form.factory' to be Public
    # Needed in PagesController to Clone and Preview Forms
    ##########################################################
    form.factory:
        class: Symfony\Component\Form\FormFactory
        arguments: ['@form.registry']
        public: true
    
    vs_cms.resources.page_categories.form:
        class: Vankosoft\CmsBundle\Form\PageCategoryForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.page_categories.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
            - '@vs_cms.repository.page_categories'
            
    vs_cms.resources.pages.form:
        class: Vankosoft\CmsBundle\Form\PageForm
        tags:
            - { name: form.type }
        arguments:  # '%vs_cms.pages.form.type.validation_groups%'
            - '%vs_cms.model.pages.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
            - '%vs_cms.model.page_categories.class%'
            
    vs_cms.resources.document_categories.form:
        class: Vankosoft\CmsBundle\Form\DocumentCategoryForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.document_categories.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
    
    vs_cms.resources.document.form:
        class: Vankosoft\CmsBundle\Form\DocumentForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.document.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
            - '%vs_cms.model.document_categories.class%'
            - '%vs_cms.model.toc_page.class%'
    
    Vankosoft\CmsBundle\Form\TocPageForm:
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.toc_page.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"

    Vankosoft\CmsBundle\Form\FileManager\UploadFileForm:
        tags:
            - { name: form.type }
    
    vs_cms.resources.file_manager.form:
        class: Vankosoft\CmsBundle\Form\VankosoftFileManagerForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.file_manager.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
    
    vs_cms.resources.file_manager_file.form:
        class: Vankosoft\CmsBundle\Form\VankosoftFileManagerFileForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.file_manager_file.class%'
            
    vs_cms.resources.helpcenter_question.form:
        class: Vankosoft\CmsBundle\Form\HelpCenterQuestionForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.helpcenter_question.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
            
    vs_cms.resources.quick_link.form:
        class: Vankosoft\CmsBundle\Form\QuickLinkForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.quick_link.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'

    vs_cms.resources.slider.form:
        class: Vankosoft\CmsBundle\Form\SliderForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.slider.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
            
    vs_cms.resources.slider_item.form:
        class: Vankosoft\CmsBundle\Form\SliderItemForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.slider_item.class%'
            - '%vs_cms.model.slider.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
    
    vs_cms.resources.banner_place.form:
        class: Vankosoft\CmsBundle\Form\BannerPlaceForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.banner_place.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
            - '@liip_imagine.filter.manager'
            
    vs_cms.resources.banner.form:
        class: Vankosoft\CmsBundle\Form\BannerForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_cms.model.banner.class%'
            - '%vs_cms.model.banner_place.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
