parameters:
    vs_cms.file_manager.taxonomy_code: file-managers
    
    #############################################################################################
    # Parameters for Shared Media File Systems and Directories
    # Need to Be Defined in Project 'services/uploader.yaml'
    # Because Not Found From Here ( I don't know why )
    #############################################################################################
    
    # League Flysystem File Systems
    vs_cms.gaufrette.app_pictures.filesystem: vs_application_app_pictures
    vs_cms.gaufrette.profile.filesystem: vs_application_profile
    vs_cms.gaufrette.filemanager.filesystem: vs_application_filemanager
    vs_cms.gaufrette.slider.filesystem: vs_application_slider
    
    # League Flysystem Shared Media Directories
    vs_cms.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_cms.filemanager_shared_media_gaufrette.profile: "%kernel.project_dir%/public/shared_media/gaufrette/profile"
    vs_cms.filemanager_shared_media_gaufrette.filemanager: "%kernel.project_dir%/public/shared_media/gaufrette/filemanager"
    vs_cms.filemanager_shared_media_gaufrette.slider: "%kernel.project_dir%/public/shared_media/gaufrette/slider"
    
    # Artgris Shared Media Directories
    vs_cms.filemanager_shared_media_artgris: '%kernel.project_dir%/public/shared_media/artgris'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_cms.file_path_generator:
        class: Vankosoft\CmsBundle\Component\Generator\UploadedFilePathGenerator

    vs_cms.app_pictures_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FileUploader
        arguments:
            - '@oneup_flysystem.vs_application_app_pictures_filesystem'
            - '@vs_cms.file_path_generator'
    
    vs_cms.profile_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FileUploader
        arguments:
            - '@oneup_flysystem.vs_application_profile_filesystem'
            - '@vs_cms.file_path_generator'
            
    vs_cms.filemanager_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FileUploader
        arguments:
            - '@oneup_flysystem.vs_application_filemanager_filesystem'
            - '@vs_cms.file_path_generator'
            
    vs_cms.slider_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FileUploader
        arguments:
            - '@oneup_flysystem.vs_application_slider_filesystem'
            - '@vs_cms.file_path_generator'
    
    vs_cms.file_manager:
        class: Vankosoft\CmsBundle\Component\FileManager
        arguments:
            - '@vs_cms.filemanager_uploader'
    
    vs_cms.oneup_uploader.post_persist:
        class: Vankosoft\CmsBundle\Component\OneupUploader\PostPersistListener
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
