imports:
    - { resource: services/controller.yaml }
    - { resource: services/security.yaml }
    - { resource: services/registration.yaml }
    - { resource: services/reset_password.yaml }
    - { resource: services/user_management.yaml }
    - { resource: services/user_profile.yaml }

services:        
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

