############################################################################################
# Vankosoft Issues Routes
############################################################################################
vs_application_project_issues_index:
    path: /project-issues
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueController::indexAction

vs_application_project_issues_create:
    path: /project-issues/new
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueController::createAction
    methods: GET|POST

vs_application_project_issues_update:
    path: /project-issues/{id}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueController::updateAction
    methods: GET|PUT

vs_application_project_issues_delete:
    path: /project-issues/{id}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueController::deleteAction
    methods: DELETE

############################################################################################
# Vankosoft Issue Comments Routes
############################################################################################
vs_application_project_issue_comments_index:
    path: /project-issues
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueCommentController::indexAction

vs_application_project_issue_comments_create:
    path: /project-issues/{issueId}/{parentCommentId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueCommentController::createAction
    methods: GET|POST

vs_application_project_issue_comments_update:
    path: /project-issues/{issueId}/{commentId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueCommentController::updateAction
    methods: GET|PUT

vs_application_project_issue_comments_delete:
    path: /project-issues/{id}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueCommentController::deleteAction
    methods: DELETE

############################################################################################
# Vankosoft Issue Tasks Routes
############################################################################################
vs_application_project_issue_tasks_index:
    path: /project-issues
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueTaskController::indexAction

vs_application_project_issue_tasks_create:
    path: /project-issues/new
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueTaskController::createAction
    methods: GET|POST

vs_application_project_issue_tasks_update:
    path: /project-issues/{issueId}/{taskId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueTaskController::updateAction
    methods: GET|PUT

vs_application_project_issue_tasks_delete:
    path: /project-issues/{id}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueTaskController::deleteAction
    methods: DELETE

############################################################################################
# Vankosoft Issues Kanbanboard Routes
############################################################################################
vs_application_project_issues_kanbanboard_show:
    path: /project-issues-board
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::showKanbanboardAction

vs_application_project_issues_kanbanboard_task_show:
    path: /project-issues-board/tasks/{taskId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::showTaskAction

vs_application_project_issues_kanbanboard_task_move:
    path: /project-issues-board/move-task/{taskId}/{pipelineId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::moveTaskAction

vs_application_project_issues_kanbanboard_task_assign_member_form:
    path: /project-issues-board/assign-member/{taskId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::getAssignMemberForm

vs_application_project_issues_kanbanboard_task_assign_member:
    path: /project-issues-board/assign-member/{taskId}/{memberId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::assignMemberAction

vs_application_project_issues_kanbanboard_pipeline_edit_task:
    path: /project-issues-board/edit-task/{pipelineId}/{taskId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::editTaskAction

vs_application_project_issues_kanbanboard_pipeline_create_task:
    path: /project-issues-board/create-task/{pipelineId}/{issueId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::createTaskAction

vs_application_project_issues_kanbanboard_task_get_subtask_form:
    path: /project-issues-board/{taskId}/get-subtask-form/{issueId}/{subTaskId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::getSubTaskFormAction

vs_application_project_issues_kanbanboard_task_create_issue:
    path: /project-issues-board/{pipelineId}/create-issue/{parentTaskId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::createIssueAction
        
vs_application_project_issues_kanbanboard_task_get_attachment_form:
    path: /project-issues-board/task-attachment/{taskId}/get-attachment-form
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::getAttachmentFormAction

vs_application_project_issues_kanbanboard_task_save_attachment:
    path: /project-issues-board/task-attachment/{taskId}/save-attachment/{attachmentId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::saveTaskAttachment

vs_application_project_issues_kanbanboard_task_download_attachment:
    path: /project-issues-board/task-attachment/{taskId}/download-attachment/{attachmentId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::downloadTaskAttachment

vs_application_project_issues_kanbanboard_task_delete_attachment:
    path: /project-issues-board/task-attachment/{taskId}/delete-attachment/{attachmentId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::deleteTaskAttachment

vs_application_project_issues_kanbanboard_task_delete_member:
    path: /project-issues-board/delete-member/{taskId}/{memberId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::deleteMemberAction

vs_application_project_issues_kanbanboard_task_get_comment_form:
    path: /project-issues-board/task-comment/{taskId}/get-comment-form
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::getCommentFormAction

vs_application_project_issues_kanbanboard_task_save_comment:
    path: /project-issues-board/task-comment/{taskId}/save-comment/{commentId}
    controller: Vankosoft\ApplicationBundle\Controller\VankosoftIssueBoardController::saveCommentFormAction
